# Change these first
owner: Bizon-Dev # Your GitHub organization or username, where this repository lives
repo: Bizon-status # The name of this repository
user-agent: Hype3808
sites:
  - name: Bizon Website
    url: https://bizonbot.eu.org
    expectedStatusCodes:
      - 200
      - 503
  - name: Bizon URL Shortener
    url: https://url.bizonbot.eu.org
    expectedStatusCodes:
      - 200
      - 503
  - name: Bizon
    check: "tcp-ping"
    url: 144.126.130.19
    port: 10000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Bizon-status
  logoUrl: https://cdn.discordapp.com/attachments/903538311468023808/932222900801527848/Bizon-website.png
  favicon: https://cdn.discordapp.com/attachments/903538311468023808/932222900801527848/Bizon-website.png
  name: Bizon Status
  url: https://bizonbot.eu.org
  introTitle: "Bizon | Status"
  theme: ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
